### ISSUE TITLE
Image Path trough Content Manager

### ISSUE THREAD

**Issue by felixlberg** [Vagr9K/gatsby-material-starter#69] opened 2019-09-26 12:41 UTC
## Description

I noticed that cover image is not saved correctly when creating a post via the content manager.

### Steps to reproduce

If you create a post manually and link the image like that in md file: `cover: 6.jpg` 
The image gets wrapped in gatsby-image-wrapper correctly. 

But if you create a post with content manager the cover is saved like that: `cover: /assets/6.jpeg`

I think the full path with `/assets/xxx.jpeg` is not included in gatsby-image-wrapper. Because of this, the image will be linked directly in `/static` instead of getting it from gatsby-image like you described in an other issue. 

### Expected result

I thought if you created content via the conten manager interface it should be wrapped in gatsby-image-wrapper as well, ho could I fix this ?

Best Regards

Felix

**Comment by Vagr9K** [comment] 2020-02-02 17:32
Sorry for the late answer. I've been rather busy recently.

As of right now I'm unable to reproduce the issue, so it might have been fixed in a newer version of the plugin.

That being said, apparently there is a plugin for Gatsby that generates Gatsby compatible paths called [`gatsby-plugin-netlify-cms-paths`](https://www.gatsbyjs.org/packages/gatsby-plugin-netlify-cms-paths/).

If the issue still persists on your end, you can give it a shot.

Again, apologies for the late reply!

**Comment by felixlberg** [comment] 2020-02-08 20:58
No worry I've fixed this already, but I will take a look at this path plugin thx for your reply.

You can look my fix [here](https://github.com/felixlberg/gatsby-material-starter/commit/240a7c47c9cccae0cffb6eec6df63c972189e8ec)

I've just added another if variable for / path, like that you can add as much additional paths for gatsby image plugin as you want. 

What you think about that ?

**Closed** 2020-02-08 22:28 UTC
